# Configurations
title: ecoWaste 사용자매뉴얼
longtitle: ecoWaste 사용자매뉴얼
author: ㈜미니소프트
email: support@ecowaste.co.kr
description: ㈜미니소프트

version: 1.0
gitbook_version: 3.2.3

url: 
baseurl: 
rss: RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# markdown render engine.
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: colorful

markdown_ext: markdown,mkdown,mkdn,mkd,md

# Permalinks
# permalink: /:categories/:year-:month-:day-:title:output_ext
permalink: /:title/

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination: ./_site
incremental: false
regenerate: true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
